project_id = "jboartixfhvifdecdufq"

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.cleanup-inactive-apps]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = true

[functions.google-drive-upload]
verify_jwt = true
